<a href="https://colab.research.google.com/github/anton-akulenko/HW1-DS/blob/main/HW1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [4]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


In [5]:
matrix_zeros = np.zeros((3, 3), dtype=int)
matrix_zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [6]:
matrix_rand = np.random.randint(1, 11, size = (5, 5))
matrix_rand

array([[ 7,  4,  4,  8,  3],
       [ 4,  6,  3,  5,  9],
       [ 6, 10,  3,  8,  6],
       [10,  6,  4,  1,  1],
       [ 1,  3, 10,  7,  5]])

#4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [7]:
R_matrix = np.random.rand(4, 4)
print(R_matrix)

[[0.56334338 0.53650027 0.23651756 0.84679865]
 [0.87271167 0.57246053 0.24210634 0.13007338]
 [0.57426752 0.9781182  0.99118763 0.5817422 ]
 [0.74775943 0.81674193 0.60261211 0.87871358]]


#5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.


In [8]:
R1_array = np.random.randint(1, 11, size = 5)
R2_array = np.random.randint(1, 11, size = 5)
print(R1_array)
print(R2_array)


[2 5 3 3 3]
[10  4  3  3  4]


In [9]:
res_add = R1_array + R2_array
res_sub = R1_array - R2_array
res_mul = R1_array * R2_array
print("ADD:", res_add)
print("SUB:", res_sub)
print("MUL:",res_mul)

ADD: [12  9  6  6  7]
SUB: [-8  1  0  0 -1]
MUL: [20 20  9  9 12]


#6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.


In [10]:
rand1_array = np.random.rand(7)
rand2_array = np.random.rand(7)
print("Scalar mul: ", np.dot(rand1_array,rand2_array))

Scalar mul:  2.2286638406154915


#7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.


In [11]:
matrix22_rand = np.random.randint(1, 11, (2, 2))
matrix23_rand = np.random.randint(1, 11, (2, 3))
print(matrix22_rand)
print(matrix23_rand)


[[4 7]
 [7 9]]
[[ 9 10  7]
 [ 4  2  9]]


In [12]:
result_matrix = np.dot(matrix22_rand, matrix23_rand)
print("(2, 2) * (2 ,3): \n", result_matrix)

(2, 2) * (2 ,3): 
 [[ 64  54  91]
 [ 99  88 130]]


#8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.


In [13]:
matrix33_rand = np.random.randint(1, 11, size = (3, 3))
print("Source (3, 3): \n",matrix33_rand)


Source (3, 3): 
 [[ 1  3  5]
 [ 8  1 10]
 [ 9  5  5]]


In [14]:
matrix33_rand_inv = np.linalg.inv(matrix33_rand)
print("Inverted (3, 3): \n", matrix33_rand_inv)

Inverted (3, 3): 
 [[-0.17307692  0.03846154  0.09615385]
 [ 0.19230769 -0.15384615  0.11538462]
 [ 0.11923077  0.08461538 -0.08846154]]


#9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


In [15]:
R_matrix = np.random.rand(4, 4)
print("Source: \n", R_matrix)
print("Transp: \n", R_matrix.T)

Source: 
 [[0.52739493 0.54353257 0.32535518 0.34938781]
 [0.56575072 0.53211464 0.12905788 0.03727731]
 [0.97240254 0.64267228 0.88939139 0.04679337]
 [0.36126246 0.66648734 0.24251095 0.66134361]]
Transp: 
 [[0.52739493 0.56575072 0.97240254 0.36126246]
 [0.54353257 0.53211464 0.64267228 0.66648734]
 [0.32535518 0.12905788 0.88939139 0.24251095]
 [0.34938781 0.03727731 0.04679337 0.66134361]]


#10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.


In [16]:
matrix34_rand = np.random.randint(1, 11, (3, 4))
vec4_rand = np.random.randint(1, 11, 4)
print("(3, 4): \n", matrix34_rand)
print("[4]: \n", vec4_rand)
print("Mul (3,4) and [4]: \n", np.dot(matrix34_rand, vec4_rand))

(3, 4): 
 [[ 2  8  2  1]
 [ 4  6  8  9]
 [ 4  2  2 10]]
[4]: 
 [6 8 2 1]
Mul (3,4) and [4]: 
 [81 97 54]


#11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.


In [17]:
matrix23_rand = np.random.rand(2, 3)
vec3_rand = np.random.rand(3)
print("(2, 3): \n", matrix23_rand)
print("[3]: \n", vec3_rand)


(2, 3): 
 [[0.15697889 0.98468702 0.4370952 ]
 [0.44395176 0.21712905 0.67937769]]
[3]: 
 [0.45129222 0.56866838 0.29525193]


In [19]:
print("Mul (2,3) and [3]: \n", np.dot(matrix23_rand, vec3_rand))

Mul (2,3) and [3]: 
 [0.75985693 0.52441397]


#12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.


In [20]:
m1_rand = np.random.randint(1, 11, (2, 2))
m2_rand = np.random.randint(1, 11, (2, 2))
print(m1_rand)
print(m2_rand)


[[8 3]
 [6 2]]
[[2 5]
 [5 9]]


In [21]:
res_mul = m1_rand * m2_rand
print("MUL scalar: \n",res_mul)

MUL scalar: 
 [[16 15]
 [30 18]]


#13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.


In [22]:
res_mul = np.dot(m1_rand, m2_rand)
print("MUL of matrix: \n",res_mul)

MUL of matrix: 
 [[31 67]
 [22 48]]


#14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.


In [23]:
matrix55_sum = np.random.randint(1, 101, size = (5, 5))
print(matrix55_sum)
print("Sum of all el matrix (5,5): \n", np.sum(matrix55_sum))

[[48 46 20 16 97]
 [ 1 48 53 41 32]
 [41 80 29 81  8]
 [18 99 96 58 87]
 [13 64 66 28 12]]
Sum of all el matrix (5,5): 
 1182


#15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.


In [24]:
m1_44 = np.random.randint(1, 11, (4, 4))
m2_44 = np.random.randint(1, 11, (4, 4))
print(m1_44)
print(m2_44)


[[ 6  9  5 10]
 [ 4  4  3 10]
 [ 3  3  3  8]
 [ 5 10  2  8]]
[[9 5 6 6]
 [6 3 3 5]
 [9 5 7 8]
 [4 2 7 1]]


In [25]:
print("Sub of matrix (4,4): \n", m1_44 - m2_44)

Sub of matrix (4,4): 
 [[-3  4 -1  4]
 [-2  1  0  5]
 [-6 -2 -4  0]
 [ 1  8 -5  7]]


#16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.


In [27]:
matrix33_slices = np.random.rand(3, 3)
print(matrix33_slices)
sum_row = np.array([sum(matrix33_slices[0,:]), sum(matrix33_slices[1,:]), sum(matrix33_slices[2,:])])


[[0.00924301 0.55562469 0.26500224]
 [0.84804685 0.68118208 0.02615245]
 [0.88402397 0.5125319  0.14557861]]


v1

In [28]:
vector_sum_column = sum_row.reshape(3, 1)
print("Sum by rows: \n", vector_sum_column)

Sum by rows: 
 [[0.82986993]
 [1.55538137]
 [1.54213449]]


v2

In [30]:
sum_row = np.sum(matrix33_slices, axis=1)
print("Sum by rows: \n", vector_sum_column)

Sum by rows: 
 [[0.82986993]
 [1.55538137]
 [1.54213449]]


#17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.


In [31]:
matrix34_suqare = np.random.randint(low=-20, high=20, size=(3, 4))
print("\n", matrix34_suqare)



 [[-19  17  -4  -3]
 [-20 -14 -20   9]
 [-17   8  19   3]]


In [32]:
print("Squares: \n", np.square(matrix34_suqare))

Squares: 
 [[361 289  16   9]
 [400 196 400  81]
 [289  64 361   9]]


#18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.


In [36]:
vector_sqrt = np.random.randint(1, 20, 4)
print("\n", vector_sqrt)



 [ 7 18 13  3]


In [37]:
print("Sqrt: ", np.sqrt(vector_sqrt))

Sqrt:  [2.64575131 4.24264069 3.60555128 1.73205081]
